# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42f73261ae1410260b8f5ca78cee27f365ae2b0e9c15eb1aaa411d3bcd31ec944de3523cd7152c5a91c0e8ef827ed3b7fb6e7f9c5691d9c37ae4bf73d6e2da27

test:
  secret_key_base: f082f398b59c124ad704060f81a9076a0d1f0bb55fa194750118c32c34517614001d2d0f57d475425d441d1276aa819067dee7aca92ca3d02c1276f8bad7e17a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
